# Numpy

This notebook includes a collection of commands and functions provided in the Numpy library that are really useful and speed up the data manipulation instructions.

## Import Numpy
I first begin by importing the nump library. I use the Python generic notation to import it and I rename it as `np` so I can use `np` instead of `numpy` everywhere.

In [30]:
import numpy as np

# Numpy array
I begin by first creating a numpy array and then accessing its elements using the index values.

In [32]:
# Define an array arr with integer elements 1,2,3 and 4
integerArray = np.array([1,2,3,4], int)

# We can access these elements by using index values
print(integerArray[0])

# We can also use ranges to access values
print(integerArray[:2])

# Find if a value exists in the array
# Returns true if value exists else returns false
2 in integerArray # Returns true

1
[1 2]


True

Numpy also provides quick methods to define an array. Basic methods include:
1. concatenation - combine arrays
2. zeros - array with all values zero
3. ones - array with all values one
4. range - define the array as a range of values

In [33]:
integerArray2 = np.array([5,6], int)

# Concatenate two arrays
print(np.concatenate((integerArray, integerArray2)))

# Array of zeros
print(np.zeros(10))

# Array of ones with type int
print(np.ones(10, dtype=int))

# Range of numbers
rangeArray = np.array(range(10), int)
print(rangeArray)

[1 2 3 4 5 6]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1 1 1 1 1 1 1 1 1 1]
[0 1 2 3 4 5 6 7 8 9]


## Multidimensional arrays

Further, Numpy library also enables us to create multidimensional arrays.
Moreover, the `reshape` function allows us to convert Numpy single dimensional arrays to multidimensional arrays and vice versa using `flatten`.

In [34]:
# Multidimensional array
floatArray = np.array([[1,2,3], [4,5,6]], float)
print(floatArray)

# Convert one dimensional to multi-dimensional arrays
rangeArray = rangeArray.reshape(5, 2)
print(rangeArray)
# and vice versa too
rangeArray = rangeArray.flatten()
print(rangeArray)

[[1. 2. 3.]
 [4. 5. 6.]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0 1 2 3 4 5 6 7 8 9]


`Concatenate` function on multidimensional arrays can be performed on any axis. For a two dimensional array (array[row][column]), to concatenate along row, we set axis as 0 (default is also 0). To concatenate along column, we set axis to 1.

In [35]:
# Concatenation of multi-dimensional arrays
arr1 = np.array([[1,2], [3,4]], int)
arr2 = np.array([[5,6], [7,8]], int)
print(np.concatenate((arr1, arr2)))

# Based on dimension 1
print(np.concatenate((arr1, arr2), axis=0))

# Based on dimension 2
print(np.concatenate((arr1, arr2), axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


## Numpy array operations
Numpy arrays allow us to directly apply a range of operations such as addition, subtraction etc. The operators are overloaded in the library which makes the process possible. The operations occur on an element by element basis.

In [43]:
print("Array 1\n {}".format(arr1))
print("Array 2\n {}".format(arr2))

# Addition
print("Array 1 + Array 2\n {}".format(arr1 + arr2))

# Multiplication
print("Array 1 * Array 2\n {}".format(arr1 * arr2))

# Square root
print("Square root of Array 1\n {}".format(np.sqrt(arr1)))

# Log
print("Log of Array 1\n {}".format(np.log(arr1)))

Array 1
 [[1 2]
 [3 4]]
Array 2
 [[5 6]
 [7 8]]
Array 1 + Array 2
 [[ 6  8]
 [10 12]]
Array 1 * Array 2
 [[ 5 12]
 [21 32]]
Square root of Array 1
 [[1.         1.41421356]
 [1.73205081 2.        ]]
Square root of Array 1
 [[0.         0.69314718]
 [1.09861229 1.38629436]]


However, these opertations will throw errors if the dimensions of the arrays are not same. There are many other operations that are available to us such as `exp`, `floor`, `abs` and many trignometric funcitons.

Operations can be specific to a given array too such as sum of all elements of the array and others. If we define the axis, then we can calculate the operations across the respective row or column.

In [60]:
# Sum of array elements
print("Sum of elements of Array 1: {}".format(arr1.sum()))

# Mean of array elements
print("Mean of elements of Array 1: {}".format(arr1.mean()))
# We can also calulate variance using var() and standard deviation using std()

# Minimum of array elements
print("Minimum of elements of Array 1: {}".format(arr1.min()))
# We can also calculate maximum value using max()

# Index of maximum of array elements can be found using arg before the funciton name
print("Index of minimum of elements of Array 1: {}".format(arr1.argmax()))
# We can also find index of minimum value using argmin()

Sum of elements of Array 1: 10
Mean of elements of Array 1: 2.5
Minimum of elements of Array 1: 1
Index of minimum of elements of Array 1: 3


In [61]:
sampleArray = np.array([[5,2,3], [3,4,5], [1,1,1]], int)
print("Sample Array\n {}".format(sampleArray))

# Get unqiue values
print("Unique values: {}".format(np.unique(sampleArray)))

# Get diagonal values
print("Diagonal\n {}".format(sampleArray.diagonal()))

# Sort values in the multidimensional array
print("Sorted\n {}".format(np.sort(sampleArray)))

Sample Array
 [[5 2 3]
 [3 4 5]
 [1 1 1]]
Unique values: [1 2 3 4 5]
Diagonal
 [5 4 1]
Sorted
 [[2 3 5]
 [3 4 5]
 [1 1 1]]


## Compare arrays
We can also use comparison operators to compare complete arrays with one another

In [50]:
# We can compare complete arrays of equal size element wise
print("Array 1 > Array 2\n{}".format(arr1 > arr2))

# We can compare elements of an array with a given value
print("Array 1 == 2\n {}".format(arr1 == 2))

Array 1 > Array 2
[[False False]
 [False False]]
Array 1 == 2
 [[False  True]
 [False False]]


## Vector and Matrix operations
Numpy is specifically famous for its efficiency while working with vectors and matrices. Some of the useful functions are described here.

In [64]:
vector = np.array([1,2,3,4], int)
matrix1 = np.array([[1,2,3], [4,5,6], [7,8,9]], int)
matrix2 = np.array([[1,1,1], [0,0,0], [1,1,1]], int)

# Dot operator
print("Dot of Matrix 1 and Matrix 2\n {}".format(np.dot(matrix1, matrix2)))

# Cross operator
print("Cross of Matrix 1 and Matrix 2\n {}".format(np.cross(matrix1, matrix2)))

# Outer operator
print("Outer of Matrix 1 and Matrix 2\n {}".format(np.outer(matrix1, matrix2)))

# Inner operator
print("Inner of Matrix 1 and Matrix 2\n {}".format(np.inner(matrix1, matrix2)))

Dot of Matrix 1 and Matrix 2
 [[ 4  4  4]
 [10 10 10]
 [16 16 16]]
Cross of Matrix 1 and Matrix 2
 [[-1  2 -1]
 [ 0  0  0]
 [-1  2 -1]]
Outer of Matrix 1 and Matrix 2
 [[1 1 1 0 0 0 1 1 1]
 [2 2 2 0 0 0 2 2 2]
 [3 3 3 0 0 0 3 3 3]
 [4 4 4 0 0 0 4 4 4]
 [5 5 5 0 0 0 5 5 5]
 [6 6 6 0 0 0 6 6 6]
 [7 7 7 0 0 0 7 7 7]
 [8 8 8 0 0 0 8 8 8]
 [9 9 9 0 0 0 9 9 9]]
Inner of Matrix 1 and Matrix 2
 [[ 6  0  6]
 [15  0 15]
 [24  0 24]]


## Random array
We can use the random function to get arrays with random values.

In [80]:
# Random array
print("Random array: {}".format(np.random.rand(5)))

# Random matrix
print("Random matrix:\n {}".format(np.random.rand(5,4)))

# Random array of integers in a range (say 0-9)
randomArray = np.floor(np.random.rand(10) * 10)
print("Random integer array: {}".format(randomArray))

# Futher simplification
print("Random matrix:\n{}".format(np.random.randint(0, 10, (2,5))))

Random array: [0.76073446 0.99345894 0.46903477 0.84603991 0.38853774]
Random matrix:
 [[0.16632713 0.58049315 0.34176713 0.94322875]
 [0.22748443 0.82143576 0.81514027 0.29211289]
 [0.96835549 0.89565579 0.48977925 0.83669168]
 [0.41939199 0.76978422 0.85281824 0.26429364]
 [0.40808517 0.33635079 0.34038655 0.9892858 ]]
Random integer array: [9. 3. 5. 7. 4. 7. 8. 8. 9. 4.]
Random matrix:
[[5 3 0 2 9]
 [0 4 4 7 8]]


# Numpy Strategies
There are a total of 4 startegies to consider in the Numpy library that can help us work better with loops.
These include:
1. Universal Functions
2. Aggregations
3. Broadcasting
4. Slicing, masking and fancy indexing

I've already adressed them in the examples above but here I would create the exact distinctions.
These functions are essential as they are very quick in their operation.

## Universal Functions
These functions operate element-wise on the elements of an array.

In [107]:
# Multiply all elements of an array by 10
arr = np.array(range(10), int)
print("Array: {}".format(arr))
print("New array: {}".format(arr * 10))

Array: [0 1 2 3 4 5 6 7 8 9]
New array: [ 0 10 20 30 40 50 60 70 80 90]


## Aggregation Functions
These functions summarize the information contained in an array.

In [92]:
# Get standard deviation of all array values
print("Standard deviation of array: {}".format(arr.std()))

Standard deviation of array: 2.8722813232690143


## Broadcasting
This defines the rules of how universal functions operate on arrays. This determines how a number might be added to a matrix, how a vector gets added to a matrix etc. 
It broadcasts the smaller of the two to match the bigger so the operation may be performed.

In [93]:
# Add a row to a matrix
mat = np.array([[1,2,3], [9,8,7]], int)
arr = np.array([1,1,1], int)
# On adding the two, arr will get broadcasted and will get added as a matrix with both rows same as [1,1,1]
print("Final sum after broadcasting:\n {}".format(mat + arr))

Final sum after broadcasting:
 [[ 2  3  4]
 [10  9  8]]


## Slicing, masking and fancy indexing
We can slice numpy arrays as and where needed or maybe get values based on index.

In [109]:
bigArray = np.array(range(10))
print("Array: {}".format(bigArray))

# Slice array from index 0 to 4
print("Array value from index 0 to 4: {}".format(bigArray[:5]))

# Masking using boolean values and operators
mask = (bigArray > 6) | (bigArray < 3)
print("Array values with mask as true: {}".format(bigArray[mask]))

# Fancy indexing
ind = [2,4,6]
print("Array values with index in list: {}".format(bigArray[ind]))

# Combine all three
print("Array values with index in list: {}".format(bigArray[bigArray > 6][:1]))

Array: [0 1 2 3 4 5 6 7 8 9]
Array value from index 0 to 4: [0 1 2 3 4]
Array values with mask as true: [0 1 2 7 8 9]
Array values with index in list: [2 4 6]
Array values with index in list: [7]


# Conclusion
Here, I have worked with a few key functions available in Numpy that facilitate array, vector and matrix multiplication. This understanding was essential as it is the basis for many other libraries such as Sklearn which uses Numpy for its algorithms.