# Numpy

This notebook includes a collection of commands and functions provided in the Numpy library that are really useful and speed up the data manipulation instructions.

## Import Numpy
I first begin by importing the nump library. I use the Python generic notation to import it and I rename it as `np` so I can use `np` instead of `numpy` everywhere.

In [30]:
import numpy as np

## Numpy array
I begin by first creating a numpy array and then accessing its elements using the index values.

In [32]:
# Define an array arr with integer elements 1,2,3 and 4
integerArray = np.array([1,2,3,4], int)

# We can access these elements by using index values
print(integerArray[0])

# We can also use ranges to access values
print(integerArray[:2])

# Find if a value exists in the array
# Returns true if value exists else returns false
2 in integerArray # Returns true

1
[1 2]


True

Numpy also provides quick methods to define an array. Basic methods include:
1. concatenation - combine arrays
2. zeros - array with all values zero
3. ones - array with all values one
4. range - define the array as a range of values

In [33]:
integerArray2 = np.array([5,6], int)

# Concatenate two arrays
print(np.concatenate((integerArray, integerArray2)))

# Array of zeros
print(np.zeros(10))

# Array of ones with type int
print(np.ones(10, dtype=int))

# Range of numbers
rangeArray = np.array(range(10), int)
print(rangeArray)

[1 2 3 4 5 6]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1 1 1 1 1 1 1 1 1 1]
[0 1 2 3 4 5 6 7 8 9]


Further, Numpy library also enables us to create multidimensional arrays.
Moreover, the `reshape` function allows us to convert Numpy single dimensional arrays to multidimensional arrays and vice versa using `flatten`.

In [34]:
# Multidimensional array
floatArray = np.array([[1,2,3], [4,5,6]], float)
print(floatArray)

# Convert one dimensional to multi-dimensional arrays
rangeArray = rangeArray.reshape(5, 2)
print(rangeArray)
# and vice versa too
rangeArray = rangeArray.flatten()
print(rangeArray)

[[1. 2. 3.]
 [4. 5. 6.]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0 1 2 3 4 5 6 7 8 9]


`Concatenate` function on multidimensional arrays can be performed on any axis. For a two dimensional array (array[row][column]), to concatenate along row, we set axis as 0 (default is also 0). To concatenate along column, we set axis to 1.

In [35]:
# Concatenation of multi-dimensional arrays
arr1 = np.array([[1,2], [3,4]], int)
arr2 = np.array([[5,6], [7,8]], int)
print(np.concatenate((arr1, arr2)))

# Based on dimension 1
print(np.concatenate((arr1, arr2), axis=0))

# Based on dimension 2
print(np.concatenate((arr1, arr2), axis=1))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


## Numpy array operations
Numpy arrays allow us to directly apply a range of operations such as addition, subtraction etc. The operators are overloaded in the library which makes the process possible. The operations occur on an element by element basis.

In [43]:
print("Array 1\n {}".format(arr1))
print("Array 2\n {}".format(arr2))

# Addition
print("Array 1 + Array 2\n {}".format(arr1 + arr2))

# Multiplication
print("Array 1 * Array 2\n {}".format(arr1 * arr2))

# Square root
print("Square root of Array 1\n {}".format(np.sqrt(arr1)))

# Log
print("Square root of Array 1\n {}".format(np.log(arr1)))

Array 1
 [[1 2]
 [3 4]]
Array 2
 [[5 6]
 [7 8]]
Array 1 + Array 2
 [[ 6  8]
 [10 12]]
Array 1 * Array 2
 [[ 5 12]
 [21 32]]
Square root of Array 1
 [[1.         1.41421356]
 [1.73205081 2.        ]]
Square root of Array 1
 [[0.         0.69314718]
 [1.09861229 1.38629436]]


However, these opertations will throw errors if the dimensions of the arrays are not same. There are many other operations that are available to us such as `exp`, `floor`, `abs` and many trignometric funcitons.

Operations can be specific to a given array too such as sum of all elements of the array and others.

In [45]:
# Sum of array elements
print("Sum of elements of Array 1: {}".format(arr1.sum()))

# Mean of array elements
print("Mean of elements of Array 1: {}".format(arr1.mean()))
# We can also calulate variance var() and standard deviation std()

# Minimum of array elements
print("Minimum of elements of Array 1: {}".format(arr1.min()))
# We can also calculate maximum value using max()

# Index of maximum of array elements can be found using arg before the funciton name
print("Index of minimum of elements of Array 1: {}".format(arr1.argmax()))
# We can also find ma

Sum of elements of Array 1: 10
Mean of elements of Array 1: 2.5
Minimum of elements of Array 1: 1
Index of minimum of elements of Array 1: 3
